# Generated by Django 4.2.8 on 2026-01-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='tickets_aud_user_id_c927d9_idx',
            old_name='tickets_au_user_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='tickets_aud_action_5db056_idx',
            old_name='tickets_au_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='tickets_aud_resourc_07389d_idx',
            old_name='tickets_au_resource_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
